"""Runtime freshness labels and fail-closed refresh gates."""
from __future__ import annotations

from datetime import date, datetime, time, timezone
from typing import Any


def parse_cutoff(value: str) -> datetime:
    text = str(value).strip()
    if len(text) == 10:
        return datetime.combine(date.fromisoformat(text), time.min, tzinfo=timezone.utc)
    parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError(f"cutoff has no timezone: {text}")
    return parsed.astimezone(timezone.utc)


def age_label(cutoff: str, now: datetime | None = None) -> str:
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    parsed = parse_cutoff(cutoff)
    seconds = max(0, int((current - parsed).total_seconds()))
    days, remainder = divmod(seconds, 86400)
    hours, _ = divmod(remainder, 3600)
    if len(str(cutoff)) == 10:
        return f"{days}d"
    if days:
        return f"{days}d {hours}u"
    minutes = remainder // 60
    if hours:
        return f"{hours}u {minutes % 60}m"
    return f"{minutes}m"


def effective_source(source: dict[str, Any], now: datetime | None = None) -> dict[str, Any]:
    """Preserve capture quality and add runtime effective quality and age."""
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    cutoff = str(source["cutoff_at"])
    parsed = parse_cutoff(cutoff)
    age_seconds = max(0, int((current - parsed).total_seconds()))
    kind = str(source["kind"])
    captured = str(source["quality"])
    effective = captured
    if kind == "BROKER_SNAPSHOT" and captured == "LIVE":
        if age_seconds <= 15 * 60:
            effective = "LIVE"
        elif age_seconds <= 4 * 86400:
            effective = "CACHED"
        else:
            effective = "STALE"
    elif captured == "DELAYED" and age_seconds > 4 * 86400:
        effective = "STALE"
    result = dict(source)
    result["captured_quality"] = captured
    result["effective_quality"] = effective
    result["age"] = age_label(cutoff, current)
    return result


def source_label(source: dict[str, Any], now: datetime | None = None) -> str:
    item = effective_source(source, now)
    quality = item["effective_quality"]
    if quality != item["captured_quality"]:
        quality = f"{quality} (captured {item['captured_quality']})"
    return f"{item['kind']} · {quality} · cutoff {item['cutoff_at']} · leeftijd {item['age']}"


def validate_fresh_refresh(
    *,
    run_started_at: datetime,
    snapshot_generated_at: str,
    market_fetched_at: str,
    market_cutoff_at: str,
    history_raw_mtime: float,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Require sources to have been collected by this refresh run.

    The history report's report timestamp can be timezone-naive, so the local raw-file mtime is
    the freshness proof for the fetch step. Final financial authority remains in
    the adapter metadata.
    """
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    start = run_started_at.astimezone(timezone.utc)
    snapshot = parse_cutoff(snapshot_generated_at)
    market = parse_cutoff(market_fetched_at)
    history_file = datetime.fromtimestamp(history_raw_mtime, timezone.utc)
    failures: list[str] = []
    tolerance_seconds = 120
    if snapshot < start.replace(microsecond=0) and (start - snapshot).total_seconds() > tolerance_seconds:
        failures.append("broker snapshot was not generated by this refresh run")
    if market < start.replace(microsecond=0) and (start - market).total_seconds() > tolerance_seconds:
        failures.append("market history was not fetched by this refresh run")
    if history_file < start and (start - history_file).total_seconds() > tolerance_seconds:
        failures.append("broker history raw XML was not refreshed by this run")
    market_session = date.fromisoformat(market_cutoff_at)
    if (current.date() - market_session).days > 4:
        failures.append("market-history completed-session cutoff is stale")
    if snapshot > current or market > current or history_file > current:
        failures.append("refresh source timestamp is in the future")
    return {
        "passed": not failures,
        "failures": failures,
        "snapshot_age_seconds": int((current - snapshot).total_seconds()),
        "market_fetch_age_seconds": int((current - market).total_seconds()),
        "market_cutoff_at": market_cutoff_at,
        "history_raw_mtime": history_file.isoformat(),
    }
